### ISSUE TITLE
How do I add the pipeline project to the automated installation

### ISSUE THREAD

**Issue by reselbob** [popularowl/cloud-squirrels#2]
Hi:

I am running the Dockerfile found here: https://github.com/popularowl/cloud-squirrels/blob/master/jenkins/jenkins-setup-docker-terraform/files/Dockerfile

I added:

`pipeline-plugin`

to this file:

https://github.com/popularowl/cloud-squirrels/blob/master/jenkins/jenkins-setup-docker-terraform/files/jenkins-plugins

hoping that a Pipeline project will appear as a project I can select when creating a Jenkins project. But, no Pipeline project appears.

I must be doing something wrong. Can you show me the error of my way, please?

Thanks in advance.

**Comment by reselbob** [comment]
Nevermind please.

There error was on my end. I deleted the blueocean plugin by mistake.

**Comment by sauliuz** [comment]
marking as solved
